### ISSUE TITLE
Notes with identical names but different casing get lost

### ISSUE THREAD

**Issue by lzilioli** [wormi4ok/evernote2md#29] opened 2021-01-04 21:14 UTC
**Problem statement**

Two notes with the same name but different casing inside of the .enex results in only a single note inside of the export.

**Example file**
The attached enex contains 2 notes:
1. this is my great note
2. This Is My Great Note

You can see that only the contents of the second entry (with the title-cased name makes it into the export).

[Archive.zip](https://github.com/wormi4ok/evernote2md/files/5766802/Archive.zip)

**Comment by wormi4ok** [comment] 2021-01-04 21:46
Thanks again, @lzilioli for an actionable bug report! Looks like you are a QA by vocation 🏅 

I can reproduce this bug. There should be two notes in the output, of course.

**Comment by ar7hur** [comment] 2021-01-07 08:32
Thanks for the great tool!
My notebook has many notes with the same name, same case (hello "Untitled"). How should the tool cope with this situation?

**Comment by wormi4ok** [comment] 2021-01-07 11:10
Hey @ar7hur ,

Since the filesystem does not allow saving files with the same name, in the output folder you should get many files named "Untitled.md", "Untitled-1.md", "Untitled-2" and so on.

**Comment by ar7hur** [comment] 2021-01-07 11:50
Oh sorry I wrongly assumed it wouldn't work since it doesn't work for the "same name, different casing" case. It works actually.

**Comment by ar7hur** [comment] 2021-01-09 11:27
Apparently you already fixed it, right? https://github.com/wormi4ok/evernote2md/blob/f98832caf82191c87cda1afed982eeaa1435dd49/notes.go#L77

**Comment by wormi4ok** [comment] 2021-01-09 12:17
Yes, I did. The issue was with the same name and different casing. The exact match is fixed since v0.6.0. 

The next release will be published tomorrow; maybe I can squeeze in a new feature along with bugfixes.

**Comment by ar7hur** [comment] 2021-01-09 15:53
Good news! Thanks again for your great work.

**Comment by wormi4ok** [comment] 2021-01-10 18:13
Fixed in version [0.14.0](https://github.com/wormi4ok/evernote2md/releases/tag/v0.14.0)

**Closed by wormi4ok** 2021-01-10 18:13 UTC
Labels: bug, good first issue
