### ISSUE TITLE
Text Highlights aren't preserved from evernote notes

### ISSUE THREAD

**Issue by shrvenkataraman** [wormi4ok/evernote2md#6] opened 2020-05-30 06:58 UTC
Hi, 

Could you help preserve highlights from evernote texts? Like say, a dirty span background insert, or a syntax highlight of sorts in the text to preserve the highlighted content?

**Comment by spetrashov** [comment] 2020-05-30 08:57
Hey, @shrvenkataraman 

I'd like to try to help you. Do you mean text marked as highlighted using Evernote formatting tools? If so, I can try to covert these highlights to a an emphasised spans in Markdown. They are usually presented as _italic_.

Could you please export a single note with an example of the highlighted text and send me?

**Comment by wormi4ok** [comment] 2020-05-30 09:24
Hey, @shrvenkataraman

I'd like to try to help you. Do you mean text marked as highlighted using Evernote formatting tools? If so, I can try to covert these highlights to a an emphasised spans in Markdown. They are usually presented as italic.

Could you please export a single note with an example of the highlighted text and send me?

**Comment by DamianMehers** [comment] 2020-08-18 06:40
Could you use HTML to highlight the text, since Markdown explicitly supports embedded HTML?

**Comment by wormi4ok** [comment] 2020-09-12 20:01
You are right, @DamianMehers. I reread the original document, and inline HTML tags should be supported by design in Markdown.

So I just published a new release [v0.10.0](https://github.com/wormi4ok/evernote2md/releases/tag/v0.10.0) that supports text highlights as suggested. I hope it will make the experience much better.

**Closed** 2020-09-26 18:39 UTC
Labels: enhancement
