### ISSUE TITLE
The content in markdown file is unreadable

### ISSUE THREAD

**Issue by qizhengyang2017** [wormi4ok/evernote2md#99] opened 2023-05-31 10:52 UTC
**Problem statement**
I exported the my notes as 印象笔记XML格式(.notes). And I used command `./evernote2md 我的笔记.notes note_new`.
The output is:
```
Done!
Converted 5 notes in 524 milliseconds
```
But the content is unreadable.
The version I used is 0.19.0. 
**Example file**
<img width="698" alt="image" src="https://github.com/wormi4ok/evernote2md/assets/27215125/624bcc3d-71c8-4026-bca0-cf0bc849f01c">

**Comment by wormi4ok** [comment] 2023-05-31 12:21
Hey @qizhengyang2017 ! Thanks for reporting this issue. May I ask you to try running the [previous evernote2md](https://github.com/wormi4ok/evernote2md/releases/tag/v0.18.2) version? In the last release I made a big change in the internal structure and need to understand if this is a regression due to the recent change or a new bug that I'm not yet aware of. Thanks in advance!

**Comment by qizhengyang2017** [comment] 2023-05-31 12:38
Actually, I used `brew` to install evernote2md at first. The version was 0.18.2. There is only a title in the output markdown file and no other content. So I installed the latested version manually.
<img width="418" alt="image" src="https://github.com/wormi4ok/evernote2md/assets/27215125/b171454b-53a1-4253-b3ec-bfb9853b6474">

**Comment by wormi4ok** [comment] 2023-05-31 17:13
Thanks for posting the sample data! It looks like the note content is encrypted - something that I've never seen before. I'll examine the content of the export file to see if it is possible to decrypt.

**Comment by qizhengyang2017** [comment] 2023-06-01 07:09
Thank you so much!

**Comment by wormi4ok** [comment] 2023-06-03 17:40
Hey, @qizhengyang2017 ! I examined the content of the export and didn't find an easy way to decrypt the content. It is properly encrypted with a secret key, not simply encoded as I initially hoped.

I couldn't find any information on encryption for the export files, neither in the Evernote documentation nor in the Evernote app I use for testing. It could be something specific to Yinxiang's SuperNote, which I don't have access to.

To help find a solution, I would kindly ask you to check if it s possible to disable encryption in the app that you use or get access to the encryption key. (If it is not possible and only SuperNote has the secret key, then the export feature can only serve for external backup purposes, not for actual export)

**Comment by wormi4ok** [comment] 2023-12-31 13:07
Not sure how else I can help here. Closing the issue.

**Closed by wormi4ok** 2023-12-31 13:07 UTC
