### ISSUE TITLE
Some content is lost if the exported note content has a color style

### ISSUE THREAD

**Issue by nbchen** [wormi4ok/evernote2md#67] opened 2022-07-02 19:30 UTC
**Problem statement**

Some content is lost if the exported note content has a color style

**Example file**

![image](https://user-images.githubusercontent.com/31268184/177014002-4d1a3135-01db-4fde-aeae-226bd6acced3.png)

**Comment by wormi4ok** [comment] 2022-07-02 20:27
Hi @nbchen, thanks for reporting the issue! Could you please upload an enex file with the paragraph on the screenshot? 
I need to check the actual markup that leads to this problem.

**Comment by wormi4ok** [comment] 2022-12-06 07:01
Hi @cardin , the fix for this issue is already merged #87, but not released because there is a smaller bug in the implementation. 

You can try to build the lastest master branch locally and check if the problem is fixed.

**Comment by wormi4ok** [comment] 2023-01-08 12:15
This issue was fixed in [v0.18.1](https://github.com/wormi4ok/evernote2md/releases/tag/v0.18.1). Please update to the latest release 🙏🏻

**Closed by wormi4ok** 2023-01-08 12:15 UTC
